#!/usr/bin/env bash

xsetroot -cursor_name left_ptr &

# gnome-keyring-daemon -d
# export $(gnome-keyring-daemon --replace)

compton -c -C &
~/.xsession-background

trayer \
    --edge top \
    --align center \
    --expand true \
    --width 10 --height 15 \
    --transparent true \
    --alpha 0 \
    --tint 0x000000 \
    --SetDockType true \
    --SetPartialStrut true \
&

xscreensaver -no-splash &
parcellite &
nm-applet &
pa-applet &

eval $(keychain --eval --agents ssh,gpg --noask)

emacs --daemon

exec xmonad
