#!/usr/bin/env bash

xsetroot -cursor_name left_ptr &

gnome-keyring-daemon -d

compton -c -C &
feh --bg-scale $HOME/Pictures/background

xmobar $HOME/dotfiles/xmonad/xmobar.hs &

trayer \
    --edge top \
    --align center \
    --expand true \
    --width 10 --height 15 \
    --transparent true \
    --alpha 0 \
    --tint 0x000000 \
    --SetDockType true \
    --SetPartialStrut true \
    &

xscreensaver -no-splash &
parcellite &
nm-applet &
pa-applet &
# dropbox

exec xmonad
