#!/usr/bin/env bash

LEFT=DisplayPort-0
MIDDLE=DisplayPort-2
RIGHT=DisplayPort-3

xrandr --output $LEFT --primary --rotate left
xrandr --output $MIDDLE --right-of $LEFT
xrandr --output $RIGHT --right-of $MIDDLE --rotate left
